twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # nous indiquons que tous nos formulaires utilisent maintent les class de boostramp 5

when@test:
    twig:
        strict_variables: true
